<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="C100-17" name="com.practice.testcases.E2ETest" tests="11" failures="1" timestamp="13 Dec 2018 04:50:07 GMT" time="129.954" errors="0">
  <testcase name="SignUp" time="29.720" classname="com.practice.testcases.E2ETest"/>
  <testcase name="invalidLogin" time="7.514" classname="com.practice.testcases.E2ETest"/>
  <testcase name="validLogin" time="9.165" classname="com.practice.testcases.E2ETest"/>
  <testcase name="loginDataDriven" time="7.411" classname="com.practice.testcases.E2ETest"/>
  <testcase name="loginDataDriven" time="4.463" classname="com.practice.testcases.E2ETest"/>
  <testcase name="loginDataDriven" time="4.470" classname="com.practice.testcases.E2ETest"/>
  <testcase name="loginDataDriven" time="4.452" classname="com.practice.testcases.E2ETest"/>
  <testcase name="loginDataDriven" time="7.188" classname="com.practice.testcases.E2ETest"/>
  <testcase name="viewProfile" time="41.575" classname="com.practice.testcases.E2ETest"/>
  <testcase name="contact" time="6.937" classname="com.practice.testcases.E2ETest"/>
  <testcase name="verifyListing" time="7.059" classname="com.practice.testcases.E2ETest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at com.practice.testcases.ListingTest.verifyListing_lowtohigh(ListingTest.java:121)
at com.practice.testcases.E2ETest.verifyListing(E2ETest.java:145)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:483)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- verifyListing -->
</testsuite> <!-- com.practice.testcases.E2ETest -->
